### ISSUE TITLE
Chore: Revamp CI/CD

### ISSUE THREAD

**Issue by hugoclrd** [stx-labs/clarinet#1078]
Our current CI/CD config

- is slow (we probably build useless stuff on each PR, we might also gain a lot of time by removing deno)
- only releases clarinet (the cli), other artifacts are published manually (clarinet, vscode extension, clarinet-sdk, others?)
- is maybe too complicated / lacks best practices and standards.

Some of the tasks are labelled as _short terms_ 🟢, the others are future improvements.
**Help from DevOps teams is wanted to validated the spec and work on the short term issues.**

#### Use semantic release? 

- Does it work with monorepo with multiple target (npm, crates, vscode, homebrew, etc)
- We would like to publish multiple tags depending on which component we want to release (clarinet, clarity-vscode, clarinet-sdk)

### Todo

- New GitHub action from scratch 🟢
- Ideally, we only want to build the components that have been modified

### Split in 3 flows 🟢

- Development flow:
    - Focus: speed
    - Trigger: a new PR is opened against `develop` branch
    - Actions:
        - Worker 1: Static analysis
             - Check code format (P0) 🟢
             - Audit dependencies (P1)
        - Worker 2: Native Linux builds (ideally debian bulleyes)
             - Build clarinet (P0) 🟢
             - Test (P0) 🟢
             - Code coverage (P1)
        - Worker 3: Wasm builds
             - Build clarinet-sdk (P0) 🟢
- Release Playbook flow:
    - Trigger: a new PR is opened against `main` branch
    - Actions:
        - Steps from the **Development flow** 🟢
        - Build and publish a docker image of clarinet, tagged with `develop` 🟢
        - Build and run tests on Windows 🟢
        - Build and run tests on macOs 🟢        
- Release flow:
    - Trigger: a new tag is being pushed (tag per component `clarinet`, `clarity-vscode`, `clarity-sdk`)
    - Actions:
        - Publish on crates.io
        - Publish on docker hub
              - clarinet 🟢 
        - Publish on NPM
              - clarity-sdk
              - stacks-devnet-js
        - Publish on Brew  
              - clarinet 🟢
        - Publish on Winget 
              - clarinet 🟢
        - Publish on VSCode marketplace
              - clarity-vscode 🟢

**Comment by lgalabru** [comment]
> Many of these actions already exist, such as publishing to brew, or code formatting. Can you clarify what you mean by this?

We have all theses steps indeed, but their order of execution is suboptimal from a DX point of view, and the current architecture apparently makes things hard to scale.
The CI was implemented a long time ago, this repo have seen some major changes since then and our last attempt getting new features added failed.
Ultimately, our goal with this refactoring is to have devops helping us getting on the right tracks, and we would then take ownership of the CI, add more features + re-use the structure as much as possible for our other repos (http://github.com/hirosystems/chainhook, http://github.com/hirosystems/hord, etc)

**Comment by CharlieC3** [comment]
@hugocaillard FYI I'm blocked until you have time to respond to the above questions since they'd have a large impact on the design of the CI/CD workflow(s).

**Comment by hugocaillard** [comment]
@CharlieC3 I've seen Ludo's message but missed yours. Sorry I very rarely miss GitHub notification 🤦‍♂️ 

> Should stacks-devnet-js be included in this list?

Yep, it's already in the list. Ludo marked it as a future improvement (with our 🟢 notation) so we could take care of that ourselve once we have the skeleton.

> Also, I don't see any component named clarinet-sdk. Can you provide a mapping between each releasable artifact and its base dir?

Ah yes, it's on ongoing project on its own branch (`feat/clarity-sdk`) so it's out of scope for now (I'll remove the green dot)

> Do you not want automated tags & releases & changelogs? If you do, the trigger would be a commit/merge into main.

Well, it would be nice, but I'm not sure it's doable in this scope. Would semantic-release know which component we want to release?

**Comment by CharlieC3** [comment]
No worries, thanks for your answers!

> Well, it would be nice, but I'm not sure it's doable in this scope. Would semantic-release know which component we want to release?

Maybe, a large part of my research for this issue was going to be on that effort. But if you would rather keep the tagging manual like it is today, then it would help simplify what needs to be done.
Just trying to make sense of what you'd like, because in Slack we discussed automated releases, but the issue indicates you were planning on keeping it manual.

This is already pushing the limits of the issue size, so maybe it would be best to separate the automated releases into another issue :)

**Comment by hugocaillard** [comment]
Well the automation part is not our main priority.
If we only have to push a tag, I think or bump a version in cargo.toml or package.json file, it's already a big win

**Comment by CharlieC3** [comment]
> Release flow:
Trigger: a new tag is being pushed (tag per component clarinet, clarity-vscode, clarity-sdk)

@hugocaillard For the current workflow, a release is triggered if all of the following is true:

1. A commit/PR is merged into `main`
2. The `version` found in the Cargo.toml (will be changed to the component's specific Cargo.toml in the rework) is _not_ found as a release in the GH repo. This indicates someone rev'd the version in the Cargo.toml and they want a new release.

AFAIK this worked pretty well. Are you aware of this previous model? Knowing this, do you still want this to be triggered by the push of a `tag`? If you want to rather keep the previous model, but adapt it to a monorepo, the resulting tag & GH release will be configured to be something like `<component name>-<component version>`.

**Comment by hugocaillard** [comment]
Yes we can keep the automatic creation of tags (so it would depends depend on `clarinet-cli/cargo.toml`'s version and in the future on others components package.json or cargo.toml versions)

(It does avoid the manual bump in package.json or cargo.toml files)

> the resulting tag & GH release will be configured to be something like `<component name>-<component version>`
Yep this is great 🙌
