### ISSUE TITLE
[BUG] `(get-block-info? time <block-id>)` always returns `(some u0)`

### ISSUE THREAD

**Issue by luizalbertocviana** [stx-labs/clarinet#310]
Great work with `clarinet`!
I appreciate your efforts in evolving this tool I use on a daily basis.

Still though, I believe I have found a bug.

I have noticed that the mentioned expression always returns the same result no matter how many blocks are mined.

Steps to reproduce:
- open `clarinet console` (version 0.28.0)
- `::advance_chain_tip 100`
- the expression `(get-block-info? time (- block-height u1))` should return `(some u0)`

I have tried different heights for `::advance_chain_tip <height>`
and also different uints for `(get-block-info? time (- block-height <uint>))`, and the result is always the same.

**Comment by obycode** [comment]
Thanks for the issue @luizalbertocviana. I'm thinking through what would be good values to use in those blocks. The documentation says that they are not guaranteed to be monotonic, and only accurate to within 2 hours, so we have a lot of flexibility for "valid" values. Can you provide some input for your use case? 

- When 100 blocks are "mined" as in your example, what would be a useful value for the time in those blocks?
- What values would be useful for your testing?
- Would it be useful to have realistic timestamps, relative to the current time?
- Could we just start from 0 and add 600 seconds for every block mined?
- Or start from the current time, and add 600 seconds for every block mined (times will be in the future)?
- Should we fuzz that 600 seconds so it varies some?

**Comment by luizalbertocviana** [comment]
Hey @obycode :)
Thanks for reply.

> When 100 blocks are "mined" as in your example, what would be a useful value for the time in those blocks?
> What values would be useful for your testing?
I believe any non-decreasing timestamp series would be enough for my unit tests.

> Would it be useful to have realistic timestamps, relative to the current time?
That would be handy for integration testing, sure, but I don't think that quite fits in unit testing.

> Could we just start from 0 and add 600 seconds for every block mined?
> Or start from the current time, and add 600 seconds for every block mined (times will be in the future)?
I believe both approaches are fine for unit testing.

> Should we fuzz that 600 seconds so it varies some?
I believe that would of some value if it could be controlled via the unit testing framework, let's say, settable by some method in Chain class.
Would that be possible?
Still in the same line, would it be possible to set a custom value instead of always skipping 600 seconds per block?

**Comment by luizalbertocviana** [comment]
Hi everyone :)

Any updates regarding this issue?
cc @obycode

**Comment by obycode** [comment]
Hi @luizalbertocviana. I'll prioritize this for the next release, on May 11.

**Comment by luizalbertocviana** [comment]
Thank you so much :)

**Comment by obycode** [comment]
If it's good enough for your testing purposes, I'm just going to return the block height multiplied by 600 as the time. No sense doing something more complex if it isn't needed. Does that work for your needs @luizalbertocviana?

**Comment by luizalbertocviana** [comment]
>If it's good enough for your testing purposes, I'm just going to return the block height multiplied by 600 as the time. No sense doing something more complex if it isn't needed. Does that work for your needs @luizalbertocviana?

Hey Brice :)

I can certainly work with that.
Thanks for your attention.
