### ISSUE TITLE
nft-burn? returns unexpected error u1

### ISSUE THREAD

**Issue by friedger** [stx-labs/clarinet#373]
The documentation says the following for nft-burn? (https://docs.stacks.co/write-smart-contracts/language-functions#nft-burn)

>If an asset identified by asset-identifier doesn't exist, this function will return an error with the following error code: (err u1)

However, calling nft-burn? with tx-sender that does not own the nft returns (err u1)  even if the asset exists.

Steps to reproduce:
burn nft by owner
https://github.com/Light-Labs/ryder-nft/blob/1708febcc0339955752951b809e35d9dfdf6573f/backend-stacks/tests/ryder-nft_test.ts#L97
==> succeeds

burn nft by user that does not own the existing id
https://github.com/Light-Labs/ryder-nft/blob/1708febcc0339955752951b809e35d9dfdf6573f/backend-stacks/tests/ryder-nft_test.ts#L114
==> burn fails (test successful)

**Comment by lgalabru** [comment]
Hey @friedger! I don't believe this is a clarinet related issue, is it? 
Thanks!

**Comment by friedger** [comment]
I opened a new one here: https://github.com/stacks-network/stacks-blockchain/issues/3153
