### ISSUE TITLE
changing stacks_node_rpc_port breaks api

### ISSUE THREAD

**Issue by hozzjss** [stx-labs/clarinet#436]
I tried to change the `stacks_node_rpc_port` to any value other than 20443 and the result would be a broken api that sends back empty responses when i use `clarinet integrate` any idea?

**Comment by lgalabru** [comment]
hey! thanks for opening this issue, it will be fixed in https://github.com/hirosystems/clarinet/pull/432 with https://github.com/hirosystems/clarinet/pull/432/commits/e51be95cfa68afee8b7e069ff6ebf6bd7b850ecc - we were missing an additional ENV on the `stacks-api` side.

**Comment by hozzjss** [comment]
Oh thanks for the answer Ludo you can close this if you want didn’t have an idea about the pr
