### ISSUE TITLE
LSP: Improve ContractMetadata handling

### ISSUE THREAD

**Issue by hugoclrd** [stx-labs/clarinet#668]
The PR #652 introduced the need to get access to get to Contract metadata as early as possible in the LSP.
With the following data:
```rs
struct ClarityMetadata {
    pub base_location: FileLocation,
    pub manifest_location: FileLocation,
    pub relative_path: String,
    pub clarity_version: ClarityVersion,
    pub epoch: StacksEpochId
}
```

This should allow to simplify these parts
https://github.com/hirosystems/clarinet/blob/04cc59f5501e7ee23dd545c36f106ebbd0d08d60/components/clarity-lsp/src/common/backend.rs#L152-L168
https://github.com/hirosystems/clarinet/blob/04cc59f5501e7ee23dd545c36f106ebbd0d08d60/components/clarinet-files/src/project_manifest.rs#L261-L282

**Comment by hugocaillard** [comment]
Raising the priority.
There a bug right now, if a contract is empty (or doesn't define any function), it's not included in the protocol state.
And the LSP relies on the ProtocolState to get the metadata. So a clarity 2 contract will be defaulted to 1 if it does not define any function.
So features like completion, hover (etc) won't work for clarity 2 functions
